version: '3'
services:
    elasticsearch:
        build:
            context: ./elasticsearch
        hostname: elasticsearch
        ports:
        - 9200:9200
        - 9300:9300
        volumes:
        - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        - ./data/elasticsearch:/usr/share/elasticsearch/data
        networks:
        - elk-internal
    elasticsearch-02:
        build:
            context: ./elasticsearch
        hostname: elasticsearch-02
        ports:
        - 9202:9200
        - 9302:9300
        volumes:
        - ./config/elasticsearch-02/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        - ./data/elasticsearch-02:/usr/share/elasticsearch/data
        networks:
        - elk-internal
    kibana:
        build:
            context: ./kibana
        hostname: kibana
        volumes:
        - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
        - ./data/kibana:/usr/share/kibana/data
        networks:
        - elk-internal
        ports:
        - 5601:5601
    logstash:
        image: docker.elastic.co/logstash/logstash:6.5.3
        hostname: logstash
        networks:
        - elk-internal
    filebeat:
        image: docker.elastic.co/beats/filebeat:6.5.3
        hostname: filebeat
        user: root
        volumes:
        - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
        - /var/lib/docker/containers:/var/lib/docker/containers:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        command: 'filebeat -e -strict.perms=false'
        networks:
        - elk-internal
    elasticsearch-hq:
        image: elastichq/elasticsearch-hq
        hostname: elasticsearch-hq
        ports:
        - 5000:5000
        networks:
        - elk-internal

networks:
    elk-internal:
