version: '3'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
        hostname: elasticsearch
        ports:
        - 9200:9200
        - 9300:9300
        volumes:
        - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        - ./data/elasticsearch:/usr/share/elasticsearch/data
        environment:
        - discovery.type=single-node
        networks:
        - elk-internal
    kibana:
        build:
            context: ./kibana
        hostname: kibana
        volumes:
        - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
        - ./data/kibana:/usr/share/kibana/data
        networks:
        - elk-internal
        ports:
        - 5601:5601
    logstash:
        image: docker.elastic.co/logstash/logstash:6.5.3
        hostname: logstash
        networks:
        - elk-internal
networks:
    elk-internal:
