node.name: elasticsearch-02
cluster.name: elasticsearch
network.host: 0.0.0.0
node.data: true
cluster.routing.allocation.disk.threshold_enabled: false
discovery.zen.ping.unicast.hosts: 
  - elasticsearch
